# Generated by Django 3.0.4 on 2020-03-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200324_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_Link',
            new_name='Movie_Links',
        ),
    ]
