# Generated by Django 3.0.4 on 2020-03-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200324_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_Links',
            new_name='MovieLinks',
        ),
    ]
