# Generated by Django 3.0.4 on 2020-03-27 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 11, 48, 3, 281802, tzinfo=utc)),
        ),
    ]
