# Generated by Django 3.0.4 on 2020-03-27 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20200327_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 12, 14, 17, 223583, tzinfo=utc)),
        ),
    ]
